### ISSUE TITLE
Recursive inclusion of vzyor.mpackage in base of GitHub project?

### ISSUE THREAD

**Issue by SlySven** [Oneymus/Vyzor#2]
Using the facility that Github offers to download the entire Vyzor package as a *.zip* file (which can of course be renamed to an *.mpackage* file) this, perhaps unintentionally **includes** the `vzyor.mpackage` file!  This is, perhaps, non-optimum (and a little recursive) - I was wondering why the file size when I re-zipped the package locally was different! :confounded:

**Comment by Oneymus** [comment]
I remove the .mpackage. The releases section of the repo will always contain the latest release for download.
