### ISSUE TITLE
Vyzor is packed wrong to allow for imports.

### ISSUE THREAD

**Issue by DevShep** [Oneymus/Vyzor#3]
When trying to import the package, import fails.  Mpackage expects all of the packages .xml files to be at the root level. As far as I can tell, .trigger isn't sufficient. :(

**Comment by SlySven** [comment]
Um, yes, this is true, from the Mudlet sources, specifically `./src/host.cpp` in the `Host::installPackage(QString, int)` C++ code:
    
            // requirements for zip packages:
            // - packages must be compressed in zip format
            // - file extension should be .mpackage (though .zip is accepted)
            // - there can only be a single xml file per package
            // - the xml file must be located in the root directory of the zip package. example: myPack.zip contains: the folder images and the file myPack.xml

**Comment by vadi2** [comment]
Source code is not documentation - we don't have the expectation that
people go reading Mudlets source code to understand how features work :)
see http://wiki.mudlet.org/w/Mudlet_Packages#How_to_create_a_Mudlet_package for
documentation on this.

**Comment by vadi2** [comment]
Super easy fix, I've sent a PR #4 in.
